busybox-httpd

diff --git a/network/services/busybox-httpd-service/files/etc/init.d/busybox-httpd b/network/services/busybox-httpd-service/files/etc/init.d/busybox-httpd
--- a/network/services/busybox-httpd-service/files/etc/init.d/busybox-httpd
+++ b/network/services/busybox-httpd-service/files/etc/init.d/busybox-httpd
@@ -22,9 +22,9 @@ start_instance()
 	local enabled
 
 	config_get_bool enabled "$cfg" 'enabled' 1
-	[ $enabled -gt 0 ] || return
+	[ "$enabled" -gt 0 ] || return
 
-	procd_open_instance $cfg
+	procd_open_instance "$cfg"
 	procd_set_param respawn
 	procd_set_param stderr 1
 	procd_set_param command /usr/sbin/httpd -f
@@ -37,10 +37,10 @@ start_instance()
 	done
 	config_get configs "$cfg" config
 	for config in $configs; do
-		if [ -e $config ]; then
+		if [ -e "$config" ]; then
 			procd_append_param command -c "$config"
 		else
-			echo "Missing $config"
+			>&2 echo "Missing $config"
 		fi
 	done
 
